---
# tasks file for postgresql

- name: Add an postgresql signing key, will not download if present
  become: yes
  apt_key:
    id: B97B0AFCAA1A47F044F244A07FCC7D46ACCC4CF8
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add postgresql repository
  become: yes
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt/ bionic-pgdg main
    state: present
    filename: postgresql

- name: install postgresql
  become: yes
  apt:
    name: "{{postgresql_packages}}"
    state: latest

- name: Set default postgres  password
  become: yes
  become_user: postgres
  postgresql_user:
    name: postgres 
    password: "{{postgres_password}}"

- name: Update configs
  become: yes
  template:
    src: "{{ item.src }}"
    dest: "/etc/postgresql/10/main/{{ item.path }}"
    mode: "{{ item.mode }}"
    owner: root
    group: root
    force: yes
  with_filetree: '../templates'
  when: item.state == 'file'
  notify: postgresql restart

- name: Enable service postgresql, and set running state
  become: yes
  service:
    name: postgresql
    enabled: yes
    state: started
